# If skip_processing = true, all other settings are ignored
[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = true
  minify = true
[build.processing.js]
  bundle = true
  minify = true
[build.processing.html]
  pretty_urls = true
[build.processing.images]
  compress = true

# Config for the Netlify Build Plugin: netlify-plugin-minify-html
[[plugins]]
  package = 'netlify-plugin-minify-html'

  # Specify which deploy contexts we'll minify HTML in.
  # Supports any Deploy Contexts available in Netlify.
  # https://docs.netlify.com/site-deploys/overview/#deploy-contexts
  [plugins.inputs]
    contexts = [
      'production',
      'branch-deploy',
      'deploy-preview'
    ]

  # Optionally, override the default options for the minification
  # https://github.com/kangax/html-minifier#options-quick-reference
  [plugins.inputs.minifierOptions]
    collapseWhitespace = true
    collapseInlineTagWhitespace = true
    processScripts = ['application/ld+json']
    conservativeCollapse = true
    minifyCSS = true
    minifyJS = true
    removeComments = true

[[redirects]]
  from = "http://bellflowerlactation.com/*"
  to = "https://www.bellflowerlactation.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://bellflowerlactation.com/*"
  to = "https://www.bellflowerlactation.com/:splat"
  status = 301
  force = true